create table if not exists import_player_data
(
    player_url  TEXT,
    player_html TEXT,
    created_on  TEXT default (datetime('now', 'subsec'))
);

create table if not exists import_player_url
(
    url          TEXT,
    created_on   TEXT default (datetime('now', 'subsec')),
    batch_name   TEXT,
    player_id    INTEGER,
    fifa_version INTEGER,
    fifa_update  INTEGER,
    idx          INTEGER
);

create table if not exists player_data
(
    player_id                      INTEGER,
    player_url                     TEXT,
    fifa_version                   INTEGER,
    fifa_update                    INTEGER,
    fifa_update_date               TEXT,
    short_name                     TEXT,
    long_name                      TEXT,
    player_positions               TEXT,
    overall                        INTEGER,
    potential                      INTEGER,
    value_eur                      INTEGER,
    wage_eur                       INTEGER,
    age                            INTEGER,
    dob                            TEXT,
    height_cm                      INTEGER,
    weight_kg                      INTEGER,
    league_id                      INTEGER,
    league_name                    TEXT,
    league_level                   INTEGER,
    club_team_id                   INTEGER,
    club_name                      TEXT,
    club_position                  TEXT,
    club_jersey_number             INTEGER,
    club_loaned_from               TEXT,
    club_joined_date               TEXT,
    club_contract_valid_until_year INTEGER,
    nationality_id                 INTEGER,
    nationality_name               TEXT,
    nation_team_id                 INTEGER,
    nation_position                TEXT,
    nation_jersey_number           INTEGER,
    preferred_foot                 TEXT,
    weak_foot                      INTEGER,
    skill_moves                    INTEGER,
    international_reputation       INTEGER,
    work_rate                      TEXT,
    body_type                      TEXT,
    real_face                      TEXT,
    release_clause_eur             INTEGER,
    player_tags                    TEXT,
    player_traits                  TEXT,
    pace                           INTEGER,
    shooting                       INTEGER,
    passing                        INTEGER,
    dribbling                      INTEGER,
    defending                      INTEGER,
    physic                         INTEGER,
    attacking_crossing             INTEGER,
    attacking_finishing            INTEGER,
    attacking_heading_accuracy     INTEGER,
    attacking_short_passing        INTEGER,
    attacking_volleys              INTEGER,
    skill_dribbling                INTEGER,
    skill_curve                    INTEGER,
    skill_fk_accuracy              INTEGER,
    skill_long_passing             INTEGER,
    skill_ball_control             INTEGER,
    movement_acceleration          INTEGER,
    movement_sprint_speed          INTEGER,
    movement_agility               INTEGER,
    movement_reactions             INTEGER,
    movement_balance               INTEGER,
    power_shot_power               INTEGER,
    power_jumping                  INTEGER,
    power_stamina                  INTEGER,
    power_strength                 INTEGER,
    power_long_shots               INTEGER,
    mentality_aggression           INTEGER,
    mentality_interceptions        INTEGER,
    mentality_positioning          INTEGER,
    mentality_vision               INTEGER,
    mentality_penalties            INTEGER,
    mentality_composure            INTEGER,
    defending_marking_awareness    INTEGER,
    defending_standing_tackle      INTEGER,
    defending_sliding_tackle       INTEGER,
    goalkeeping_diving             INTEGER,
    goalkeeping_handling           INTEGER,
    goalkeeping_kicking            INTEGER,
    goalkeeping_positioning        INTEGER,
    goalkeeping_reflexes           INTEGER,
    goalkeeping_speed              INTEGER,
    ls                             TEXT,
    st                             TEXT,
    rs                             TEXT,
    lw                             TEXT,
    lf                             TEXT,
    cf                             TEXT,
    rf                             TEXT,
    rw                             TEXT,
    lam                            TEXT,
    cam                            TEXT,
    ram                            TEXT,
    lm                             TEXT,
    lcm                            TEXT,
    cm                             TEXT,
    rcm                            TEXT,
    rm                             TEXT,
    lwb                            TEXT,
    ldm                            TEXT,
    cdm                            TEXT,
    rdm                            TEXT,
    rwb                            TEXT,
    lb                             TEXT,
    lcb                            TEXT,
    cb                             TEXT,
    rcb                            TEXT,
    rb                             TEXT,
    gk                             TEXT,
    player_face_url                TEXT
);

create table if not exists player_url
(
    player_url_id INTEGER
        constraint pk_player_url primary key autoincrement,
    player_url    TEXT
        constraint ak_player_url_2 unique,
    player_id     INTEGER,
    fifa_version  INTEGER,
    fifa_update   INTEGER,
    status        INTEGER default 0 not null,
    idx           INTEGER,
    constraint ak_player_url unique (player_id, fifa_version, fifa_update)
);

